version: '3'

services:
  chat-app-node-1:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      "3001:3001"
    environment:
      - PORT=3001
      - CORS_ORIGIN=${CORS_ORIGIN}
      - REDIS_URL=${REDIS_URL}